### ISSUE TITLE
Are ConstraintTemplates available?

### ISSUE THREAD

**Issue by shinebayar-g** [GoogleCloudPlatform/gke-policy-library#132]
It looks like only Constraints are available. Are ConstraintTemplates available somewhere?

**Comment by apeabody** [comment]
Hi @shinebayar-g - The [Policy Controller Constraint Template Library](https://cloud.google.com/anthos-config-management/docs/latest/reference/constraint-template-library) is installed as a option when installing [Policy Controller](https://cloud.google.com/anthos-config-management/docs/how-to/installing-policy-controller#verify_the_constraint_template_library_installation).

**Comment by shinebayar-g** [comment]
Yeah we were using Policy Controller until standalone installation was deprecated and moved into GKE Enterprise. So I was wondering if source library is around somewhere.

**Comment by apeabody** [comment]
Hi @shinebayar-g - The [Policy Controller Constraint Template Library](https://cloud.google.com/anthos-config-management/docs/latest/reference/constraint-template-library) is part of the [Policy Controller](https://cloud.google.com/anthos-config-management/docs/how-to/installing-policy-controller#verify_the_constraint_template_library_installation) product. However open-source templates can also be found at [OPA Gatekeeper Library](https://open-policy-agent.github.io/gatekeeper-library/website/).
