### ISSUE TITLE
PSS Restricted v2022 installation fails because of missing K8sPSSRunAsNonRoot CRD

### ISSUE THREAD

**Issue by sshcherbakov** [GoogleCloudPlatform/gke-policy-library#173]
I have tried installing "PSS Restricted v2022" bundle via Config Sync to an Anthos on Bare Metal cluster with 
* Template Library
* Pod Security Standards Baseline v2022
* Pod Security Standards Restricted v2022

bundles installed via Policy Controller in Cloud Console. 

In Config Sync I see multiple error messages about missing CRDs:
<img width="1153" alt="Screenshot 2024-04-30 at 12 00 14" src="https://github.com/GoogleCloudPlatform/gke-policy-library/assets/3210551/5675932a-6b49-4cbf-949e-eb06c12e74bb">

When I'm trying to install "PSS Restricted v2022" bundle from this project directly using the installation command
```
kubectl apply -k https://github.com/GoogleCloudPlatform/gke-policy-library.git/anthos-bundles/pss-restricted-v2022
```
I get the following error during installation:
```
error: resource mapping not found for name: "pss-restricted-v2022-running-as-non-root" namespace: "" from "https://github.com/GoogleCloudPlatform/gke-policy-library.git/anthos-bundles/pss-restricted-v2022": no matches for kind "K8sPSSRunAsNonRoot" in version "constraints.gatekeeper.sh/v1beta1"
ensure CRDs are installed first
```

Where can I find the K8sPSSRunAsNonRoot constrainttemplate definition?

**Comment by sshcherbakov** [comment]
The K8sPSSRunAsNonRoot has been introduced in Policy Controller 1.17.3. Once I upgraded to that version the bundle was successfully installed. Closing the ticket.

**Comment by lesaux** [comment]
thank you for documenting this! I ran into this today.
